
function dict() {
    let word = prompt("Enter a word");

    let dictionary = {
        abandon: "Abandon: To leave something behind",
        ability: "Ability: The power to do something",
        active: "Full of energy",
        allow: "Allow: To let something happen",
        agree: "To have the same opinion",
        angry: "feeling mad or upset",
        bright: "Full of light or color",
        balance: "A steady position",
        beautiful: "Very pleasing to look at",
        brave: "Not afraid of danger",
        busy: "having a lot of work",
        come: "to move toward someone",
        careful: "Giving attention to avoid danger",
        celebrate: "To enjoy a special event",
        clean: "Not dirty",
        comfort: "Feeling of ease",
        create: "To make something new",
        complete: "Finished",
        danger: "Risk of harm",
        decide: "To choose",
        deep: "Far from the surface",
        destroy: "To damage badly",
        develop: "To grow or improve",
        drink: "To take liquid",
        Difficult: "hard to do",
        different: "Not the same",
        dream: "Thoughts during sleep or hopes",
        easy: "Not hard",
        eat: "To have food",
        educate: "To teach",
        effort: "Hard work",
        enjoy: "To like something",
        enough: "As much as needed",
        excited: "Very happy or eager",
        explain: "To make clear",
        family: "parents and relatives",
        free: "Not busy",
        friend: "A person you like and trust",
        famous: "Known by many people",
        fast: "Moving quickly",
        fear: "Feeling of being scared",
        finish: "To and something",
        freedom: "Being free",
        friendly: "Kind and nice",
        future: "Time ahead",
        generous: "Willing to give",
        gentle: "Soft and kind",
        glad: "Happy",
        goal: "Something you want to achieve",
        great: "Very good",
        grow: "To increase in size",
        happy: "Feeling joy",
        healthy: "Free form illness",
        help: "To assist",
        house: "A place to live",
        honest: "Thruthful",
        hope: "wish for something good",
        hunger: "Need for food",
        idea: "a thought or plan",
        important: "very necessary",
        improve: "to make better",
        include: "to make part of something",
        information: "facts or details",
        interest: "feeling of wanting to know more",
        invite: "to ask someone to come",
        ignore: "to not pay attention",
        increase: "to become bigger or more",
        inside: "the inner part",
        intelligent: "very smart",
        introduce: "to present someone",
        idea: "a new thought",
        interest: "money earned on savings",
        injure: "To hurt someone",
        income: "money earned",
        ill: "not healthy",
        issue: "A problem or topic",
        imagine: "To think creatively",
        kind: "Caring and friendly",
        learn: "To gain knowledge",
        listen: "To hear carefully",
        love: "Strong affection",
        lucky: "Having good fortune",
        mistake: "An  error",
        move: "To change position",
        nature: "The natural world",
        necessary: "Needed",
        nice: "pleasant",
        observe: "To watch carefully",
        oscillate: "To swing or move back and forth in a regular rhythm",
        opulent: "Rich, luxurious, or showing great wealth",
        omniscient: "Knowing everything or having infinite knowledge",
        obfuscate: "To make something obscure, unclear, or intentionally confusing",
        obdurate: "Stubbornly persistent or refusing to change one's mind",
        patient: "Able to wait calmly",
        peace: "Calm and quiet",
        place: "locations",
        power: "strength or energy",
        protect: "To keep safe",
        proud: "feeling good about yourself",
        professional: "having special skills, training, or education for a job",
        quick: "Fast",
        quiet: "making little noise",
        respect: "To value someone",
        safe: "Free from danger",
        share: "To give part to others",
        speak: "To say words",
        sleep: "To rest",
        sad: "Feeling unhappy",
        school: "A place to learn",
        strong: "Having power",
        success: "Achieving a goal",
        support: "To help",
        teach: "To give knowledge",
        thankful: "Feeling grateful",
        think: "To use your mind",
        trust: "To believe in someone",
        truth: "What is real",
        useful: "Helpful",
        urgent: "Requiring immediate action or attention",
        unique: "Being the only one of its kind; special",
        upset: "To disturb someone emotionally or cause distress",
        urban: "Relating to a city or town",
        unite: "To join together to form a single group",
        undo: "To reverse or cancel an action",
        up: "Moving toward a higher place or position",
        us: "Referring to the speaker and at least one other person",
        victory: "Winning",
        wait: "To stay until something happens",
        walk: "To move on foot",
        want: "To wish or desire something",
        warm: "having some heat",
        wash: "to clean with water",
        watch: "to look at carefully",
        water: "a clear liquid we drink",
        weak: "not strong",
        wear: "to have clothes on your body",
        weather: "the condition of air (hot, cold, rain)",
        welcome: "to greet someone kindly",
        well: "in good health",
    };

    let meaning = dictionary[word.toLowerCase()] || "the word is not in the dictionary";
    document.getElementById("result").innerText = meaning;
}