
function dict() {
    let word = prompt("Enter a word");

    let dictionary = {
        abandon:"Abandon: To leave something behind",
        ability:"Ability: The power to do something",
        active:"Full of energy",
        allow:"Allow: To let something happen",
        agree:"To have the same opinion",
        angry:"feeling mad or upset",
        bright:"Full of light or color",
        balance:"A steady position",
        beautiful:"Very pleasing to look at",
        brave:"Not afraid of danger",
        busy:"having a lot of work",
        come:"to move toward someone",
        careful:"Giving attention to avoid danger",
        celebrate:"To enjoy a special event",
        clean:"Not dirty",
        corner:"where two sides meet",
        courage:"bravery",
       cover:"to put something over",
        crowd:"a large group of people",
       cut:"to divide with something sharp",
       customer:"a person who buys something",
       cute:"attractive in a sweet way",
       cycle:"a bike or a repeated process",
       call:"to speak to someone by phone or voice",
       camp:"to stay outdoors",
        comfort:"Feeling of ease",
        create:"To make something new",
       carry:"to hold and move something",
       catch:"to grab something",
       choose:"to pick one thing",
       close:"near, not far",
       clever:"smart and quick to learn",
       color:"how something looks",
       cook:"to prepare food",
       copy:"to make the same thing again",
        correct:"right, not wrong",
         count:"to say numbers in order",
         cap:"a type of hat",
          card:"thick paper",
          careless:"not careful",
          center:"the middle",
         chance:"an opportunity",
        check:"to look at something carefully",
        complete:"Finished",
        danger:"Risk of harm",
        decide:"To choose",
        deep:"Far from the surface",
        destroy:"To damage badly",
        develop:"To grow or improve",
        drink:"To take liquid",
        Difficult:"hard to do",
        different:"Not the same",
        dream:"Thoughts during sleep or hopes",
        easy:"Not hard",
        eat:"To have food",
        educate:"To teach",
        effort:"Hard work",
        enjoy:"To like something",
        enough:"As much as needed",
        excited:"Very happy or eager",
        eager:"Very interested or excited",
        early:"Before the usual time",
        earn:"To get money by working",
        earth:"The planet we live on",
        easy:"Not hard",
        effect:"Result or change",
        effort:"Hard work",
        elder:"Older person",
        electric:"Using electricity",
        empty:"Having nothing inside",
        encourage:"To give support",
        end:"Finish",
        enemy:"A person who is against you",
        energy:"Power to do work",
        enjoy:"To like something",
        enough:"As much as needed",
        enter:"To go inside",
        equal:"Same in value",
        escape:"To get away",
        especially:"Particularly",
        event:"Something that happens",
        example:"A sample or model",
        excellent:"Very good",
        excited:"Very happy or eager",
        exercise:"Physical activity",
        exist:"To be real",
        expect:"To think something will happen",
        explain:"To make something clear",
        earnxplore:"To search or discover",
        extra:"More than usual",
        family:"parents and relatives",
        free:"Not busy",
        friend:"A person you like and trust",
        famous:"Known by many people",
        fast:"Moving quickly",
        fear:"Feeling of being scared",
        finish:"To and something",
        freedom:"Being free",
        friendly:"Kind and nice",
        future:"Time ahead",
        generous:"Willing to give",
        gentle: "Soft and kind",
        glad: "Happy",
        goal: "Something you want to achieve",
        great: "Very good",
        grow: "To increase in size",
        gift : "something given to someone",
         green:"a color",
         game:"an activity for fun",
        guide :"a person who shows the way",
        gold:"a yellow precious metal",
        girl:"a female child",
        give:"to hand something to someone",
        go:"to move or travel",
        get:"to receive or obtain",
        ground:"the surface of the earth",
        group:"a number of people or things",
        guess:"to try to answer without being sure",
        garden:"a place where plants grow",
        glass:"a hard, clear material",
        glow:"to shine softly",
        gate:"a door or entrance",
        giant:"very big",
        giant:"very big",
       gifted:"having special ability",
       greet:"to say hello",
      grace:"elegance or kindness",
      grateful:"thankful",
      grain:"small hard seeds",
     grass:"green plants on the ground",
      guilty:"responsible for a wrong act",
     guard:"a person who protects",
     gain:"to get or increase",
     global:"related to the whole world",
     golden:"made of gold or gold-colored",
     glance:"a quick look",
      gather:"to come together",
       gentleness:"the quality of being gentle",
        growth:"the process of growing",  
        goodness:"the quality of being good",
        happy: "Feeling joy",
        healthy:"Free form illness",
        help:"To assist",
        house:"A place to live",
        honest:"Thruthful",
        hope:"wish for something good",
        hunger:"Need for food",
        idea:"a thought or plan",
        important:"very necessary",
        improve:"to make better",
        include:"to make part of something",
        information:"facts or details",
        interest:"feeling of wanting to know more",
        invite:"to ask someone to come",
        ignore:"to not pay attention",
        increase:"to become bigger or more",
        inside:"the inner part",
        intelligent:"very smart",
        introduce:"to present someone",
        idea:"a new thought",
        interest:"money earned on savings",
        injure:"To hurt someone",
        income:"money earned",
        ill:"not healthy",
        issue:"A problem or topic",
        imagine:"To think creatively",
        kind:"Caring and friendly",
        learn:"To gain knowledge",
        listen:"To hear carefully",
        love:"Strong affection",
        lucky:"Having good fortune",
        match:"A game or equal thing",
        measure:"To find size or amount",
        medicine:"Used to treat illness",
        middle:"Center part",
        moment:"A short time",
        mountain:"A very high hill",
        moral:"Lesson or rule of right behavior",
        mood:"A feeling",
        move:"To change place",
        music:"Pleasant sound",
        must:"Very necessary",
        machine:"A tool that works",
        magic:"Something surprising",
        main:"Most important",
        mark:"A sign or score",
        memory:"Ability to remember",
        message:"Information sent to someone",
        mind:"The thinking part",
        minute:"A short time",
        modern:"New or recent",
        money:"Used to buy things",
        month:"One part of a year",
        make:"To create or build",
        manage:"To control or handle",
        many:"A large number",
        market:"A place to buy and sell",
        matter:"Something important",
        meaning:"What something shows",
        meet:"To see someone",
        member:"Part of a group",
        nature:"The natural world",
        necessary:"Needed",
        nice:"pleasant",
        observe:"To watch carefully",
        oscillate:"To swing or move back and forth in a regular rhythm",
        opulent:"Rich, luxurious, or showing great wealth",
        omniscient:"Knowing everything or having infinite knowledge",
        obfuscate:"To make something obscure, unclear, or intentionally confusing",
        obdurate:"Stubbornly persistent or refusing to change one's mind",
        patient:"Able to wait calmly",
        peace:"Calm and quiet",
        place:"locations",
        power:"strength or energy",
        protect:"To keep safe",
        proud:"feeling good about yourself",
        professional:"having special skills, training, or education for a job",
        quick:"Fast",
        quiet:"making little noise",
        respect:"To value someone",
        safe:"Free from danger",
        share:"To give part to others",
        speak:"To say words",
        sleep:"To rest",
        sad:"Feeling unhappy",
        school:"A place to learn",
        strong:"Having power",
        success:"Achieving a goal",
        support:"To help",
        teach:"To give knowledge",
        thankful:"Feeling grateful",
        think:"To use your mind",
        trust:"To believe in someone",
        truth:"What is real",
        useful:"Helpful",
        urgent:"Requiring immediate action or attention",
        unique:"Being the only one of its kind; special",
        upset:"To disturb someone emotionally or cause distress",
        urban:"Relating to a city or town",
        unite:"To join together to form a single group",
        undo:"To reverse or cancel an action",
        up:"Moving toward a higher place or position",
        us:"Referring to the speaker and at least one other person",
        victory:"Winning",
        wait:"To stay until something happens",
        walk:"To move on foot",
        want:"To wish or desire something",
        warm:"having some heat",
        wash:"to clean with water",
        watch:"to look at carefully",
        water:"a clear liquid we drink",
        weak:"not strong",
        wear:"to have clothes on your body",
        weather:"the condition of air (hot, cold, rain)",
        welcome:"to greet someone kindly",
        well:"in good health",
        xray:"a type of picture used by doctors to see inside the body",
        xylophone:"a musical instrument with wooden bars",
       xenophobia:"fear or dislike of people from other countries",
       xerox:"a copy made by a machine",
      xylem:"a plant tissue that carries water",
      xenial:"friendly to guests",
      xaxis:"the horizontal line on a graph",
      xfactor:"a special quality that makes someone different",
      yes:"used to agree",
       young:"not old",
       yellow:"a color",
      yummy:"very tasty",
      year:"12 months",
      yard:"an outdoor area or 3 feet",
      yawn:"to open the mouth when tired",
       yell:"to shout loudly",
       youth:"the time of being young",
       yourself:"the person you are talking to",
       yesterday:"the day before today",
        yogurt:"a dairy food",
       yolk:"the yellow part of an egg",
       yacht:"a large boat",
      yarn:"thread used for knitting",
      yawn:"to open the mouth wide (tired)",
      yield:"to produce or give",
      yoke:"a wooden bar for animals",
       yummy:"delicious",
       youngster:"a young person",
      yours:"belonging to you",
      youthful:"young in appearance",
       yearly:"once every year",
       yelp:"a short sharp cry",
       yonder:"at a distance",
       yardstick:"a measuring stick",
       yesman:"a person who always agrees",
       yawningly:"in a boring way",
       yummylooking:"looking tasty",
       yawned:"past form of yawn",
    };

    let meaning = dictionary[word.toLowerCase()] || "the word is not in the dictionary";
    document.getElementById("result").innerText = meaning;
}